# Generated by Django 3.2.15 on 2022-09-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='contacts',
            field=models.ManyToManyField(editable=False, related_name='assets', to='core.Person'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='documents',
            field=models.ManyToManyField(editable=False, related_name='assets', to='core.Document'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manufacturer'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.ManyToManyField(editable=False, related_name='assets', to='core.Note'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pictures',
            field=models.ManyToManyField(editable=False, related_name='assets', to='core.Picture'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchases',
            field=models.ManyToManyField(editable=False, related_name='assets', to='core.Purchase'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='room',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(editable=False, related_name='assets', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='videos',
            field=models.ManyToManyField(editable=False, related_name='assets', to='core.Video'),
        ),
        migrations.AlterField(
            model_name='person',
            name='departments',
            field=models.ManyToManyField(editable=False, related_name='people', to='core.Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='office',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
    ]
