# Generated by Django 3.2.15 on 2022-11-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221115_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='documents',
            field=models.ManyToManyField(editable=False, related_name='purchases', to='core.Document'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
