# Generated by Django 3.2.15 on 2022-11-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221116_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Student'), (3, 'Staff'), (4, 'Faculty'), (5, 'Technician')], default=0),
        ),
    ]
