# Generated by Django 3.2.15 on 2022-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='edorda',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='purchase',
            name='funding',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Grant Funded'), (2, 'Capital Equipment'), (2, 'Start-up')], null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vreference',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
