# Generated by Django 3.2.15 on 2022-12-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221207_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='funding',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Grant Funded'), (2, 'Capital Equipment'), (3, 'Start-up')], null=True),
        ),
    ]
