# Generated by Django 3.2.15 on 2022-12-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_purchase_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Technician'), (2, 'Faculty'), (3, 'Staff'), (4, 'Student'), (5, 'Other'), (6, 'Purchaser')], default=0),
        ),
    ]
