# Generated by Django 3.2.15 on 2023-08-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_department_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=8, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('details', models.TextField(blank=True, max_length=4096)),
                ('budget', models.CharField(blank=True, max_length=128)),
                ('course', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('kind', models.SmallIntegerField(blank=True, choices=[(1, 'None'), (2, 'Class'), (3, 'High Priority'), (4, 'Research'), (5, 'Low Priority'), (6, 'Other')], null=True)),
                ('category', models.SmallIntegerField(blank=True, choices=[(1, 'None'), (2, 'Activity Support'), (3, 'Machining/Welding/Cutting'), (4, 'Instrument Maintenance/Repair'), (5, 'Preventative Maintenance Schedule'), (6, 'MBH Building Support'), (7, 'Custom Fabrication'), (8, 'Apparatus Maintenance/Repair')], null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Complete'), (4, 'Cancelled')], null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('opened', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('closed', models.DateField(blank=True, null=True)),
                ('assets', models.ManyToManyField(editable=False, related_name='jobs', to='core.Asset')),
                ('customers', models.ManyToManyField(editable=False, related_name='jobs_as_customer', to='core.Person')),
                ('departments', models.ManyToManyField(editable=False, related_name='jobs', to='core.Department')),
                ('documents', models.ManyToManyField(editable=False, related_name='jobs', to='core.Document')),
                ('notes', models.ManyToManyField(editable=False, related_name='jobs', to='core.Note')),
                ('pictures', models.ManyToManyField(editable=False, related_name='jobs', to='core.Picture')),
                ('rooms', models.ManyToManyField(editable=False, related_name='jobs', to='core.Room')),
                ('technicians', models.ManyToManyField(editable=False, related_name='jobs_as_technician', to='core.Person')),
                ('videos', models.ManyToManyField(editable=False, related_name='jobs', to='core.Video')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=1024)),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
            ],
        ),
    ]
