# Generated by Django 3.2.15 on 2024-02-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_work_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='summary',
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
