# Generated by Django 3.2.15 on 2024-02-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20240206_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmi',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.job'),
        ),
        migrations.AlterField(
            model_name='pmi',
            name='next',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
