# Generated by Django 3.2.15 on 2024-02-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240206_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('content', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/')),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='files',
            field=models.ManyToManyField(editable=False, related_name='assets', to='core.File'),
        ),
        migrations.AddField(
            model_name='job',
            name='files',
            field=models.ManyToManyField(editable=False, related_name='jobs', to='core.File'),
        ),
        migrations.AddField(
            model_name='pmi',
            name='files',
            field=models.ManyToManyField(editable=False, related_name='_core_pmi_files_+', to='core.File'),
        ),
    ]
