# Generated by Django 3.2.15 on 2024-02-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20240207_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='job',
            name='videos',
        ),
        migrations.AlterField(
            model_name='pmi',
            name='files',
            field=models.ManyToManyField(editable=False, related_name='pmis', to='core.File'),
        ),
    ]
