# Generated by Django 3.2.15 on 2024-02-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20240208_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmi',
            name='next',
            field=models.DateField(blank=True, null=True),
        ),
    ]
