# Generated by Django 3.2.15 on 2024-02-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_pmi_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmi',
            name='last_job',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
