# Generated by Django 3.2.15 on 2024-02-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pmi_last_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='files',
            field=models.ManyToManyField(editable=False, related_name='purchases', to='core.File'),
        ),
    ]
