# Generated by Django 3.2.15 on 2024-02-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_purchase_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person'),
        ),
        migrations.AlterField(
            model_name='file',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='files/%Y/%m/'),
        ),
    ]
