# Generated by Django 3.2.15 on 2024-02-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20240215_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='video',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='documents',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
