# Generated by Django 3.2.15 on 2024-02-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20240215_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='contributor',
        ),
    ]
