# Generated by Django 3.2.15 on 2024-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_note_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='files/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='file',
            name='picture',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='files/%Y/%m/'),
        ),
    ]
