# Generated by Django 3.2.15 on 2024-03-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20240220_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('quality', models.SmallIntegerField(choices=[(0, '720p'), (1, '1080p')], default=0)),
                ('task_id', models.UUIDField()),
                ('downloader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
            ],
        ),
    ]
