# Generated by Django 3.2.15 on 2024-03-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='task_id',
        ),
        migrations.AddField(
            model_name='download',
            name='status',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='download',
            name='status_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='downloader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.person'),
        ),
        migrations.AlterField(
            model_name='download',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
